
[hashids]
  length = 12
  secret = "6ab6122836cfef95f8db"

[language]
  local = "zh-cn"

[mail]
  host = "smtp.163.com"
  pass = "JPIXSNOGYCZMXWGV"
  port = 465
  to = "17602196562@163.com"
  user = "17602196562@163.com"

[mysql]

  [mysql.base]
    connmaxlifetime = 60
    maxidleconn = 60
    maxopenconn = 10

  [mysql.read]
    addr = "127.0.0.1:3306"
    name = "go_gin_api"
    pass = "root"
    user = "root"

  [mysql.write]
    addr = "127.0.0.1:3306"
    name = "go_gin_api"
    pass = "root"
    user = "root"

[redis]
  addr = "127.0.0.1:6379"
  db = "0"
  maxretries = 3
  minidleconns = 5
  pass = ""
  poolsize = 10
